name: CI

on:
  # Run on pull requests
  pull_request:
  
  # Run on pushes to main branch
  push:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      
      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      
      - name: Install dependencies
        run: bun install
      
      - name: Run lint
        run: bun lint
      
      - name: Run tests
        run: bun test
